spring:
  application:
    name: payment-service
  profiles:
    active: chaos-monkey
  docker:
    compose:
      file: payment-service/compose.yaml
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - chaosmonkey
accounting-service:
  url: http://localhost:8081
third-party-service:
  url: http://localhost:8082